name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0/5 * * * *'
  # - cron:  '0 1 * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |-
        curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY" \
          | jq '.data | sort_by(.id)' > models.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
